name: mobile_shop
description: "A e-commerce app for deliveries "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  app_ui:
    path: packages/app_ui
  # data_provider: 
  #   path: packages/data_provider
  # dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  # path_provider: ^2.1.5
  # url_launcher: ^6.3.1
  # envied: ^1.1.1
  # auto_size_text: ^3.0.0
  equatable: ^2.0.7
  talker_flutter: ^4.7.2
  talker_bloc_logger: ^4.7.2
  # talker_dio_logger: ^4.7.2
  talker: ^4.7.2
  get_it: ^8.0.3

  auto_route: ^10.0.1
  connectivity_plus: ^6.1.3
  marquee: ^2.3.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  sentry_flutter: ^8.14.2
  cupertino_icons: ^1.0.8
  mobile_scanner: ^6.0.9
  carousel_slider_plus: ^7.1.0

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: mobile-shop
  org: iuhd
