name: app_ui
description: App UI Component Library.
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  # fonts:
    # - family: LobsterTwo
    #   fonts:
